# Exercice d'application

## Affichage sur des données INSEE sur le salaire en fonction du diplôme et du sexe

Données brutes disponibles : http://www.insee.fr/
Données mises en forme: http://mapsi.lip6.fr/uploads/Main/salaire2010INSEE.csv

**Correspondances des lignes:**
 - Aucun ou Certificat d’études primaires
 - Brevet des collèges
 - CAP ou BEP
 - Baccalauréat
 - IUT, BTS, diplôme de 1er cycle universitaire (DEUG, L1, L2) ou diplôme équivalent
 - Diplôme supérieur à Baccalauréat +2
 - Diplôme de 2ème ou 3ème cycle universitaire
 - Diplôme d'une grande école (ingénieur, commerce)
 
**Correspondances des colonnes:**
 - Moyenne des heures travaillées
 - Salaire horaire
Les 2 colonnes sont répétées 3 fois: Ensemble de la population / Femmes / Homme

Code de chargement des données:
```python
import numpy as np
data = np.loadtxt("data/dataSalaire.csv", delimiter=';')
```

### Questions

A l'aide de la méthode scatter, tracer les salaires moyens en fonction des diplômes pour:
 - L'ensemble de la population (en vert)
 - Les femmes (en rose -n'ayons pas peur des clichés-)
 - Les hommes (en bleu)
 
Ajouter des titres sur les axes (xlabel, ylabel)
Modifier l'axe des x pour afficher le diplôme avec le vecteur de textes suivant:
```python
diplomes = ["Aucun", "BEPC", "CAP/BEP", "Bac", "IUT, BTS, DEUG", ">Bac+2", "Master/Phd", "Ecole Ing/com"]
```


In [1]:
import numpy as np

# après avoir télécharger le fichier et l'avoir déplacé dans le répertoire data
data = np.loadtxt("data/dataSalaire.csv", delimiter=';')

# premier affichage
print(data)

# second affichage... => A FAIRE !

[[1473.     16.33 1423.     15.06 1505.     17.09]
 [1490.     18.01 1444.     16.68 1533.     19.19]
 [1509.     17.41 1456.     16.36 1545.     18.08]
 [1531.     20.21 1468.     18.43 1585.     21.64]
 [1539.     23.04 1462.     21.35 1631.     24.85]
 [1635.     33.71 1536.     28.36 1715.     37.6 ]
 [1594.     31.07 1516.     27.32 1677.     34.72]
 [1755.     40.74 1664.     34.35 1784.     42.64]]


## Histogramme amélioré

L'objectif de cet exercice est de construire un histogramme très spécifique sur les données suivantes:
- regrouper toutes les notes $<5$
- regrouper les notes entre 5 et 8 inclus
- regrouper les notes suivantes 2 par 2 entre 8 et 16
- puis 1 par 1 au dessus.
Faire l'affichage avec la commmande ```bar``` de matplotlib

In [3]:
# génération de notes => Arbitraire, pas besoin de comprendre le processus de génération
N= 100
notes = np.maximum(np.minimum(np.round(np.random.randn(N)*4+9,1),20),0)

print(notes)

# faire les affichages demandés

[ 2.4  1.4 11.4  7.8  9.9  7.7  5.2 10.1  5.3  9.  10.4 10.6  7.9  8.3
  8.2  0.  14.7 13.5  3.9 14.   9.6  8.2 10.4 13.9  4.5  4.5 11.5  9.2
  8.7  4.   7.5 13.6  7.7  8.4 12.   4.9 14.7 12.7  8.1  8.6  5.   0.
  2.6 10.7  8.6 12.6 11.  11.8 12.9 12.8  6.8 11.4  5.3 16.   7.4  9.
  0.   4.2  9.1 12.   9.8  9.8  7.4 11.4 16.1 15.7 11.2  9.2  9.8 12.2
  8.8  5.2  9.3  8.2  7.1  9.7  7.   2.7 14.1 14.8  7.2  8.5  7.3  5.5
  8.9 10.2 11.6 12.6  7.  11.3  5.6 10.8 16.1 10.5  2.2  4.4 11.8  7.7
  8.5  7.6]


## Scatter plot et code couleur

Soit des données 2D (aléatoires)... Nous allons essayer de les colorer pour leur donner du sens

1. Afficher un scatter plot où tous les points sont bleus
1. Afficher un scatter plot où tous les points sont bleus 
    1. sauf ceux dont l'absisse est supérieure à 0.75 (à afficher en rouge)
1. Afficher un scatter plot dont la couleur est *proportionnelle* à l'axe des ordonnées
1. Afficher un scatter plot dont la couleur est *proportionnelle* à l'axe des ordonnées ET dont le rayon est proportionnel à l'axe des absisses

** Documentation: ** https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html

In [2]:
X = np.random.rand(100,2)

print(X)

# faire les affichages


[[0.34380919 0.09940023]
 [0.63667574 0.14886719]
 [0.17131159 0.10319421]
 [0.97768626 0.25931485]
 [0.82888366 0.35687838]
 [0.99408125 0.93610417]
 [0.90198952 0.07324714]
 [0.22976824 0.48417053]
 [0.93884791 0.43070095]
 [0.5032714  0.72239184]
 [0.99101539 0.48699754]
 [0.22408393 0.27345649]
 [0.70144444 0.74314382]
 [0.48327829 0.45030633]
 [0.98648722 0.6609687 ]
 [0.66327343 0.5994233 ]
 [0.38526345 0.27601899]
 [0.97775783 0.43326197]
 [0.65082205 0.64632128]
 [0.1390228  0.42540817]
 [0.70417589 0.27285549]
 [0.42109474 0.74693349]
 [0.19071999 0.52271145]
 [0.92948264 0.69137119]
 [0.81784705 0.2394114 ]
 [0.15701649 0.54642556]
 [0.53852581 0.78146541]
 [0.46735545 0.9632562 ]
 [0.77362557 0.47074144]
 [0.98673833 0.57376108]
 [0.26670571 0.36399008]
 [0.29112195 0.15172611]
 [0.38002    0.76953292]
 [0.7418801  0.73882115]
 [0.97526046 0.92355493]
 [0.03542787 0.7744015 ]
 [0.82178631 0.70583787]
 [0.99636118 0.14964511]
 [0.85878327 0.03192089]
 [0.22630185 0.0158044 ]


## Premier contact avec les données USPS

Les données USPS sont très classiques en machine learning, il s'agit de chiffres de code postaux dont on souhaite automatiser la reconnaissance (pour du tri de lettres).

Voici quelques exemples d'images de cette base : 

<img src="./data/usps.png" title="Quelques exemples">

Y. LeCun, O. Matan, B. Boser, J. S. Denker, et al. (1990) *Handwritten zip code recognition with multilayer networks*. In ICPR, volume II, pages 35–40.

Le code suivant permet de charger les données... Chaque ligne de $X$ correspond à une image *mise en ligne* (256 pixels).

1. Tirer quelques images aléatoirement puis les remettre en forme (```reshape``` vers un carré de 16x16 pixels) puis les afficher
1. Afficher l'image moyenne constituée de tous les ```3``` présents dans la base de données
1. afficher l'image moyenne des ```3``` *moins* l'image moyenne des ```6```
    1. Peut-on imaginer un algorithme simple qui trie les ```3``` par rapport aux ```6``` à partir de ce résultat graphique?
1. afficher l'image moyenne des ```3``` *moins* l'image moyenne de tous les autres chiffres. En développant la question précédente, on aurait un algorithme de détection des 3... Et on pourrait faire de même pour chaque chiffre.


In [4]:
import pickle as pkl
data = pkl.load(open("data/usps.pkl",'rb')) 
# data est un dictionnaire contenant les champs explicites X_train, X_test, Y_train, Y_test
X = np.array(data["X_test"],dtype=float)    # contient 1 image par ligne (256 colonnes = 16x16 pixels)
Y = data["Y_test"]                          # contient les étiquettes associées aux images

